@domain = http://localhost:3000
 @jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo3LCJleHAiOjE2NDY1OTg2MjB9.6TXNmMXsT7wak8Ih7Q_drj01ZzdDzpe0n96SsRlgg_0


### Create user
POST {{domain}}/users
Content-Type: application/json

{
  "name": "Guy Wilson",
  "email": "guy@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}
### show user
GET http://127.0.0.1:3000/users/2

### Update user
PATCH http://127.0.0.1:3000/users/5
Content-Type: application/json

{
  "first_name": "Jeffrey",
  "last_name": "Walton",
  "email": "jeffrey@gmail.com",
  "password_digest": "password"
}

### Users Delete
DELETE http://127.0.0.1:3000/users/6

### Sessions request
POST {{domain}}/sessions
Content-Type: application/json

{
  "email": "guy@gmail.com",
  "password": "password"
}
###
_______________________________________
### Workouts index
GET {{domain}}/workouts
Authorization: Bearer {{ jwt }}

### Workouts Show - This is working as it should
GET {{domain}}/workouts/19
Authorization: Bearer {{ jwt }}

### Delete Workout
DELETE {{domain}}/workouts/19
Authorization: Bearer {{ jwt }}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}


### Photos create
# POST http://localhost:3000/photos
# Authorization: Bearer {{jwt}}
# Content-Type: application/json
# {
#   "name": "Test name",
#   "width": 640,
#   "height": 480
# }


###
POST {{domain}}/workout_exercises
Content-Type: application/json

{
  "workout_id": 20
  
}

### Workout_Exercises Index
GET {{domain}}/workout_exercises 


###
POST http://127.0.0.1:3000/workouts 
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "name": "Saturday hard workout",
  "muscle_group": "quads",
  "exercise_ids": ["3293", "3294", "2355"]
}

### Updat Workout
PATCH {{domain}}/workouts/12
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "name": "Fast workout",
  "muscle_group": "delts",
  "exercise_ids": ["0002", "0003", "0004", "1122", "0006"]

}

### All Exercises (currently set to get 5 exercises)
GET {{domain}}/exercises

### Exercises based on what muscle -set to get 5
GET {{domain}}/exercises-muscle/quads


###exercise based on exercise id
GET {{domain}}/exercises/1368

###
