@domain = http://localhost:3000
 @jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxNiwiZXhwIjoxNjQ3NTM3OTY0fQ.nMcFJPGUyEYuBUVqXwxeiOTay7qOwxPQrUeboPfATF8

### Sessions request
POST {{domain}}/sessions
Content-Type: application/json

{
  "email": "aiden@gmail.com",
  "password": "password"
}

### Create user
POST {{domain}}/users
Content-Type: application/json

{
  "name": " erin Jackson",
  "email": "erin@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}
### show user
GET http://127.0.0.1:3000/users/me
Authorization: Bearer {{ jwt }}

### Update user
PATCH http://127.0.0.1:3000/users/me
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "name": "Friendly Jones",
  "email": "friendly@gmail.com"
  
}

### Users Delete
DELETE http://127.0.0.1:3000/users/me
Authorization: Bearer {{ jwt }}


###
_______________________________________
### Workouts index
GET {{domain}}/workouts/me
Authorization: Bearer {{ jwt }}

### Workouts Show 
GET {{domain}}/workouts/me/82
Authorization: Bearer {{ jwt }}

### DELETE Workout
DELETE {{domain}}/workouts/me/95
Authorization: Bearer {{ jwt }}

### workout edit? 
POST {{domain}}/workout_exercises
Content-Type: application/json

{
  "workout_id": 66,
  "exerciseDB_id": "3204"
  
}


### Workout create
POST http://127.0.0.1:3000/workouts/me
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "name": "tuesday test workout",
  "muscle_group": "mixed muscles",
  "exercise_ids": ["3223", "0009", "3223", "0010", "1708"]
}

### Updat Workout
PATCH {{domain}}/workouts/34
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "name": "Fast kout",
  "muscle_group": "biceps"
}

### All Exercises (currently set to get 5 exercises)
GET {{domain}}/exercises
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "target": "biceps",
  "exercise_count": 4

}

### Exercises by equipment
GET {{domain}}/exercises-equipment
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "equipment": "cable",
  "exercise_count": 4

}
###
POST {{domain}}/db-exercises
Content-Type: application/json

{
  "name": "barbell biceps curl (with arm blaster)",
  "bodyPart": "upper arms",
  "equipment": "barbell",
  "gifUrl": "http://d205bpvrqc9yn1.cloudfront.net/2407.gif",
  "exerciseDB_id": "2407",
  "target": "biceps"
}

###
### Loop through all exercises and put them in the database
POST {{domain}}/db-exercises
Content-Type: application/json

### Exercises based on what muscle -set to get 5
GET {{domain}}/exercises-muscle/quads


###exercise based on exercise id
GET {{domain}}/exercises/3223

###

###Workout_Exercise delete

DELETE {{domain}}/workout_exercises/me/150
Authorization: Bearer {{ jwt }}

###DO NOT SEND REQUEST - TOO MANY API CALLS
#GET {{domain}}/db-exercises