@domain = http://localhost:3000
 @jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo3LCJleHAiOjE2NDY1MjE3NTh9.gK9ciCaRTTZqoblzZmhKx_At2zE5UKgFNZ3SGcWAApw


### Create user
POST {{domain}}/users
Content-Type: application/json

{
  "name": "Guy Wilson",
  "email": "guy@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}
### show user
GET http://127.0.0.1:3000/users/2

### Update user
PATCH http://127.0.0.1:3000/users/5
Content-Type: application/json

{
  "first_name": "Jeffrey",
  "last_name": "Walton",
  "email": "jeffrey@gmail.com",
  "password_digest": "password"
}

### Users Delete
DELETE http://127.0.0.1:3000/users/6

### Sessions request
POST {{domain}}/sessions
Content-Type: application/json

{
  "email": "guy@gmail.com",
  "password": "password"
}
###
_______________________________________
### Workouts index
GET {{domain}}/workouts
Authorization: Bearer {{ jwt }}

### Workouts Show - This is working as it should
GET {{domain}}/workouts/14
Authorization: Bearer {{ jwt }}
###
POST http://127.0.0.1:3000/workouts 
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "name": "Killing This",
  "muscle_group": "quads",
  "exercise_ids": ["1368", "3293", "0007"]
}
### Delete Workout
DELETE {{domain}}/workouts/18
Authorization: Bearer {{ jwt }}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}


### Photos create
# POST http://localhost:3000/photos
# Authorization: Bearer {{jwt}}
# Content-Type: application/json
# {
#   "name": "Test name",
#   "width": 640,
#   "height": 480
# }


###
POST {{domain}}/workout_exercises
Content-Type: application/json

{
  "workout_id": 2,
  "exerciseDB_id": "3422"
}

### Workout_Exercises Index
POST {{domain}}/workout_exercises

### All Exercises
GET {{domain}}/exercises

### Exercises based on what muscle
GET {{domain}}/exercises-muscle/biceps


###exercise based on exercise id
GET {{domain}}/exercises/1512

###
